# ================= SERVER =================
server.port=8081

# ================= DATABASE (H2) =================
spring.datasource.url=jdbc:h2:file:./data/budgetwise-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ================= JPA =================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ================= H2 CONSOLE =================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ================= OPTIONAL (prevents lazy errors) =================
spring.jpa.open-in-view=false